// Code generated by protoc-gen-go. DO NOT EDIT.
// source: article/v1/rpc.proto

package littlebird_article_v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	math "math"
)

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ListArticlesRequest struct {
	Offset               int64    `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit                int64    `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListArticlesRequest) Reset()         { *m = ListArticlesRequest{} }
func (m *ListArticlesRequest) String() string { return proto.CompactTextString(m) }
func (*ListArticlesRequest) ProtoMessage()    {}
func (*ListArticlesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7eb0a1d4c43f90a9, []int{0}
}
func (m *ListArticlesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListArticlesRequest.Unmarshal(m, b)
}
func (m *ListArticlesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListArticlesRequest.Marshal(b, m, deterministic)
}
func (m *ListArticlesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListArticlesRequest.Merge(m, src)
}
func (m *ListArticlesRequest) XXX_Size() int {
	return xxx_messageInfo_ListArticlesRequest.Size(m)
}
func (m *ListArticlesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListArticlesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListArticlesRequest proto.InternalMessageInfo

func (m *ListArticlesRequest) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *ListArticlesRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type ListArticlesResponse struct {
	Articles             []*Article `protobuf:"bytes,1,rep,name=articles,proto3" json:"articles,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ListArticlesResponse) Reset()         { *m = ListArticlesResponse{} }
func (m *ListArticlesResponse) String() string { return proto.CompactTextString(m) }
func (*ListArticlesResponse) ProtoMessage()    {}
func (*ListArticlesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7eb0a1d4c43f90a9, []int{1}
}
func (m *ListArticlesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListArticlesResponse.Unmarshal(m, b)
}
func (m *ListArticlesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListArticlesResponse.Marshal(b, m, deterministic)
}
func (m *ListArticlesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListArticlesResponse.Merge(m, src)
}
func (m *ListArticlesResponse) XXX_Size() int {
	return xxx_messageInfo_ListArticlesResponse.Size(m)
}
func (m *ListArticlesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListArticlesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListArticlesResponse proto.InternalMessageInfo

func (m *ListArticlesResponse) GetArticles() []*Article {
	if m != nil {
		return m.Articles
	}
	return nil
}

type Article struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=Title,proto3" json:"Title,omitempty"`
	Content              string   `protobuf:"bytes,3,opt,name=Content,proto3" json:"Content,omitempty"`
	Markdown             string   `protobuf:"bytes,4,opt,name=Markdown,proto3" json:"Markdown,omitempty"`
	LastUpdate           string   `protobuf:"bytes,5,opt,name=LastUpdate,proto3" json:"LastUpdate,omitempty"`
	CreatedBy            string   `protobuf:"bytes,6,opt,name=CreatedBy,proto3" json:"CreatedBy,omitempty"`
	CreatedByID          string   `protobuf:"bytes,7,opt,name=CreatedByID,proto3" json:"CreatedByID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Article) Reset()         { *m = Article{} }
func (m *Article) String() string { return proto.CompactTextString(m) }
func (*Article) ProtoMessage()    {}
func (*Article) Descriptor() ([]byte, []int) {
	return fileDescriptor_7eb0a1d4c43f90a9, []int{2}
}
func (m *Article) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Article.Unmarshal(m, b)
}
func (m *Article) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Article.Marshal(b, m, deterministic)
}
func (m *Article) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Article.Merge(m, src)
}
func (m *Article) XXX_Size() int {
	return xxx_messageInfo_Article.Size(m)
}
func (m *Article) XXX_DiscardUnknown() {
	xxx_messageInfo_Article.DiscardUnknown(m)
}

var xxx_messageInfo_Article proto.InternalMessageInfo

func (m *Article) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Article) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Article) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Article) GetMarkdown() string {
	if m != nil {
		return m.Markdown
	}
	return ""
}

func (m *Article) GetLastUpdate() string {
	if m != nil {
		return m.LastUpdate
	}
	return ""
}

func (m *Article) GetCreatedBy() string {
	if m != nil {
		return m.CreatedBy
	}
	return ""
}

func (m *Article) GetCreatedByID() string {
	if m != nil {
		return m.CreatedByID
	}
	return ""
}

func init() {
	proto.RegisterType((*ListArticlesRequest)(nil), "littlebird.article.v1.ListArticlesRequest")
	proto.RegisterType((*ListArticlesResponse)(nil), "littlebird.article.v1.ListArticlesResponse")
	proto.RegisterType((*Article)(nil), "littlebird.article.v1.Article")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ArticleServiceClient is the client API for ArticleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ArticleServiceClient interface {
	// List articles
	List(ctx context.Context, in *ListArticlesRequest, opts ...grpc.CallOption) (*ListArticlesResponse, error)
}

type articleServiceClient struct {
	cc *grpc.ClientConn
}

func NewArticleServiceClient(cc *grpc.ClientConn) ArticleServiceClient {
	return &articleServiceClient{cc}
}

func (c *articleServiceClient) List(ctx context.Context, in *ListArticlesRequest, opts ...grpc.CallOption) (*ListArticlesResponse, error) {
	out := new(ListArticlesResponse)
	err := c.cc.Invoke(ctx, "/littlebird.article.v1.ArticleService/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ArticleServiceServer is the server API for ArticleService service.
type ArticleServiceServer interface {
	// List articles
	List(context.Context, *ListArticlesRequest) (*ListArticlesResponse, error)
}

func RegisterArticleServiceServer(s *grpc.Server, srv ArticleServiceServer) {
	s.RegisterService(&_ArticleService_serviceDesc, srv)
}

func _ArticleService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListArticlesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/littlebird.article.v1.ArticleService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleServiceServer).List(ctx, req.(*ListArticlesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ArticleService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "littlebird.article.v1.ArticleService",
	HandlerType: (*ArticleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _ArticleService_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "article/v1/rpc.proto",
}

func init() { proto.RegisterFile("article/v1/rpc.proto", fileDescriptor_7eb0a1d4c43f90a9) }

var fileDescriptor_7eb0a1d4c43f90a9 = []byte{
	// 337 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0x4d, 0x4e, 0xc2, 0x40,
	0x14, 0x4e, 0xcb, 0xff, 0xc3, 0xb0, 0x18, 0xab, 0x99, 0x10, 0x42, 0x48, 0x57, 0x44, 0x93, 0x36,
	0xe0, 0xce, 0x9d, 0xc2, 0x86, 0x04, 0x37, 0x55, 0x0f, 0x30, 0xd0, 0x07, 0x99, 0x58, 0x3b, 0x75,
	0xe6, 0x81, 0x71, 0xeb, 0xc6, 0x03, 0x78, 0x26, 0x4f, 0xe0, 0x15, 0x3c, 0x88, 0x61, 0x5a, 0x10,
	0x13, 0x4c, 0x5c, 0x7e, 0x3f, 0x6f, 0xf2, 0xcd, 0xf7, 0x1e, 0x78, 0x42, 0x93, 0x9c, 0x27, 0x18,
	0xae, 0x07, 0xa1, 0xce, 0xe6, 0x41, 0xa6, 0x15, 0x29, 0x76, 0x92, 0x48, 0xa2, 0x04, 0x67, 0x52,
	0xc7, 0x41, 0x61, 0x08, 0xd6, 0x83, 0x76, 0x67, 0xa9, 0xd4, 0x32, 0xc1, 0x50, 0x64, 0x32, 0x14,
	0x69, 0xaa, 0x48, 0x90, 0x54, 0xa9, 0xc9, 0x87, 0xfc, 0x11, 0x1c, 0x4f, 0xa5, 0xa1, 0xab, 0xdc,
	0x6f, 0x22, 0x7c, 0x5a, 0xa1, 0x21, 0x76, 0x0a, 0x55, 0xb5, 0x58, 0x18, 0x24, 0xee, 0xf4, 0x9c,
	0x7e, 0x29, 0x2a, 0x10, 0xf3, 0xa0, 0x92, 0xc8, 0x47, 0x49, 0xdc, 0xb5, 0x74, 0x0e, 0xfc, 0x08,
	0xbc, 0xdf, 0x8f, 0x98, 0x4c, 0xa5, 0x06, 0xd9, 0x25, 0xd4, 0x8b, 0x20, 0x86, 0x3b, 0xbd, 0x52,
	0xbf, 0x39, 0xec, 0x06, 0x07, 0x43, 0x06, 0xc5, 0x68, 0xb4, 0xf3, 0xfb, 0x1f, 0x0e, 0xd4, 0x0a,
	0x96, 0xb5, 0xc0, 0x9d, 0x8c, 0x6d, 0x92, 0x46, 0xe4, 0x4e, 0xc6, 0x9b, 0x14, 0x77, 0x92, 0x12,
	0xb4, 0x29, 0x1a, 0x51, 0x0e, 0x18, 0x87, 0xda, 0x48, 0xa5, 0x84, 0x29, 0xf1, 0x92, 0xe5, 0xb7,
	0x90, 0xb5, 0xa1, 0x7e, 0x23, 0xf4, 0x43, 0xac, 0x9e, 0x53, 0x5e, 0xb6, 0xd2, 0x0e, 0xb3, 0x2e,
	0xc0, 0x54, 0x18, 0xba, 0xcf, 0x62, 0x41, 0xc8, 0x2b, 0x56, 0xdd, 0x63, 0x58, 0x07, 0x1a, 0x23,
	0x8d, 0x82, 0x30, 0xbe, 0x7e, 0xe1, 0x55, 0x2b, 0xff, 0x10, 0xac, 0x07, 0xcd, 0x1d, 0x98, 0x8c,
	0x79, 0xcd, 0xea, 0xfb, 0xd4, 0xf0, 0xcd, 0x81, 0x56, 0xf1, 0x8f, 0x5b, 0xd4, 0x6b, 0x39, 0x47,
	0xb6, 0x82, 0xf2, 0xa6, 0x2e, 0x76, 0xf6, 0x47, 0x19, 0x07, 0x16, 0xd2, 0x3e, 0xff, 0x97, 0x37,
	0xef, 0xdd, 0xf7, 0x5e, 0x3f, 0xbf, 0xde, 0xdd, 0x16, 0x3b, 0xda, 0x1c, 0xc8, 0xb6, 0xd1, 0x59,
	0xd5, 0x6e, 0xfc, 0xe2, 0x3b, 0x00, 0x00, 0xff, 0xff, 0xc1, 0x89, 0x03, 0xec, 0x3e, 0x02, 0x00,
	0x00,
}
